fix: remove button-foucs and add margin for box
blocklet/install-on-abtnode pull request #8
Opened 2020-11-15 13:58 UTC by leermao

- 调整项目样式
- 更细readme

2020-11-15 13:59 UTC, leermao commented
![image](https://user-images.githubusercontent.com/11629887/99186803-c7bf3100-278d-11eb-96eb-2fded155e1df.png)

2020-11-16 01:29 UTC, wangshijun requested changes

2020-11-16 01:29 UTC, wangshijun commented on CHANGELOG.md
> +
changelog 如果自动生成的不对，自己好好写下吧

2020-11-18 10:30 UTC, wangshijun approved these changes

2020-11-18 10:30 UTC, wangshijun approved these changes

2020-11-18 10:30 UTC, merged